
FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
#RUN npm config set strict-ssl false
#RUN npm install npm@latest -g
RUN npm install

COPY . .
RUN chown node /app/node_modules

CMD ["npm", "run", "start"]


## docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app 6b318929c8091334f09
